## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [1]:
from sklearn.model_selection import train_test_split
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [3]:
X_train1, X_test1, y_train1, y_test1 = train_test_split(X[:40], y[:40], test_size=10)

In [4]:
X_train2, X_test2, y_train2, y_test2 = train_test_split(X[40:], y[40:], test_size=10)

In [5]:
x_train, y_train = np.concatenate([X_train1, X_train2]), np.concatenate([y_train1, y_train2])

In [6]:
x_test, y_test = np.concatenate([X_test1, X_test2]), np.concatenate([y_test1, y_test2])

In [7]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [8]:
x_test

array([[ 65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74],
       [ 15,  16,  17,  18,  19],
       [180, 181, 182, 183, 184],
       [170, 171, 172, 173, 174],
       [ 10,  11,  12,  13,  14],
       [ 90,  91,  92,  93,  94],
       [ 60,  61,  62,  63,  64],
       [150, 151, 152, 153, 154],
       [145, 146, 147, 148, 149],
       [535, 536, 537, 538, 539],
       [350, 351, 352, 353, 354],
       [255, 256, 257, 258, 259],
       [925, 926, 927, 928, 929],
       [245, 246, 247, 248, 249],
       [935, 936, 937, 938, 939],
       [400, 401, 402, 403, 404],
       [320, 321, 322, 323, 324],
       [815, 816, 817, 818, 819],
       [425, 426, 427, 428, 429]])